In [41]:
import numpy as np
import numpy.matlib 
  
def myPow( matrix, n):
  if n == 0:
     return 1
  if n == 2:
    return np.dot(matrix,matrix)%65535
  if not n%2:
    return myPow(myPow(matrix,n/2),2)
  else:    
    
    return np.dot(matrix,(myPow(myPow(matrix,n//2),2)))
  
k=int(input("k="))

x=[[1,2,3],
   [4,5,6],
   [7,8,9]]

row=len(x)
col=len(x[0])
matrix_1=numpy.matlib.eye(row, col,0, int)#对角线是1
matrix_0=np.matlib.zeros((row,col))#全0方阵
a=np.hstack((x,matrix_1))
b=np.hstack((matrix_0,matrix_1))
c=np.vstack((a,b))
F1_F1=np.vstack((x,x))

print("F1_F1=",F1_F1)
print("b=",c)

matrix=myPow(c,k-1)

exFn=matrix*F1_F1

Fn=exFn[0:len(x),0:len(x)]

print("Fn=",Fn)







k=1000000000
F1_F1= [[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
b= [[1. 2. 3. 1. 0. 0.]
 [4. 5. 6. 0. 1. 0.]
 [7. 8. 9. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Fn= [[ 5287255.  6583760.  7880265.]
 [12857950. 15995045. 19132140.]
 [20428645. 25406330. 30384015.]]
