In [18]:
import numpy as np
from numpy import *

A=int(input("A="))
B=int(input("B="))
D=int(input("D="))

matrix=np.zeros((A,B))
# print("matrix=",matrix)
for i in range(D):
  a=int(input("a="))
  b=int(input("b="))
  d=int(input("d="))
  if d>matrix[a][b]:
    matrix[a][b]=d
print("matrix=",matrix)
# matrix=[[6590,3073,0,0,0],
#        [0,0,0,4573,0],
#        [0,0,789,0,0],
#        [0,0,0,975,0],
#        [0,0,204,631,0]]
array_a=[]
array_b=[]
list_a=[]
list_b=[]


for i in range(A):
  max_a=0
#   max_b=0
  for j in range(B):
    if matrix[i][j]>max_a:
      max_a=matrix[i][j]
      x=i
      y=j
  if max_a in array_a:
    continue
  elif max_a!=0:
    list_a.append((x,y))
    array_a.append(max_a)
print("array_a",array_a)  
print("list_a=",list_a)
  
  
for i in range(A):
#   max_a=0
  max_b=0
  for j in range(B):
    if matrix[j][i]>max_b:
      max_b=matrix[j][i]
      x=j
      y=i
  if max_b in array_b:
    continue
  elif max_b!=0:
    list_b.append((x,y))
    array_b.append(max_b)

print("array_b",array_b)  
print("list_b=",list_b)

array_G=array_a
list_G=list_a
for i in range(len(array_b)):
  if array_b[i] in array_G:
    continue
  else:
    array_G.append(array_b[i])
    list_G.append(list_b[i])
    
print("array_G",array_G)
print("list_G",list_G)

output=10000*(A+B)
for i in range(len(array_G)):
  output -= array_G[i]

print("output=",output)
  
  

A=5
B=5
D=10
a=0
b=4
d=4372
a=2
b=0
d=16
a=2
b=0
d=146
a=2
b=4
d=326
a=2
b=4
d=2133
a=2
b=4
d=9220
a=3
b=1
d=8364
a=3
b=2
d=6336
a=3
b=4
d=8833
a=4
b=1
d=2339
matrix= [[   0.    0.    0.    0. 4372.]
 [   0.    0.    0.    0.    0.]
 [ 146.    0.    0.    0. 9220.]
 [   0. 8364. 6336.    0. 8833.]
 [   0. 2339.    0.    0.    0.]]
array_a [4372.0, 9220.0, 8833.0, 2339.0]
list_a= [(0, 4), (2, 4), (3, 4), (4, 1)]
array_b [146.0, 8364.0, 6336.0, 9220.0]
list_b= [(2, 0), (3, 1), (3, 2), (2, 4)]
array_G [4372.0, 9220.0, 8833.0, 2339.0, 146.0, 8364.0, 6336.0]
list_G [(0, 4), (2, 4), (3, 4), (4, 1), (2, 0), (3, 1), (3, 2)]
output= 60390.0
